[tool.poetry]
name = "parking_management_system"
version = "1.0.0"
license = ""
description = ""
readme = "README.md"
authors = ["Developer <cu.18bcs2174@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.masonry.api"
